### PR TITLE
fix: update linkedin issuer url

### LINKED ISSUE #1533: Error when using oauth with provider linkedin_oidc - Error getting user profile from external provider
### Version
@nuxtjs/supabase: v1.2.0
nuxt: v3.6.5

When using signInWithOAuth with linkedin_oidc

```
const client = useSupabaseClient()
const result = await client.auth.signInWithOAuth({
    provider: 'linkedin_oidc',
    options: {
        redirectTo: '...'
    }
})
```

It redirects back to the redirectTo URL with the following query params:
`error=server_error&error_code=500&error_description=Error+getting+user+profile+from+external+provider#error=server_error&error_code=500&error_description=Error+getting+user+profile+from+external+provider`

When checking the Auth logs in the Supabase platform I found this error:
`error: oidc: id token issued by a different provider, expected \"https://www.linkedin.com\" got \"https://www.linkedin.com/oauth\"","level":"error","method":"GET","msg":"500: Error getting user profile from external provider`

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Linkedin introduced a breaking change by changing the issuer url in their 
discover document from `https://linkedin.com` to `https://linkedin.com/oauth` 

* Fixes #1533, #1534, [#22711](https://github.com/orgs/supabase/discussions/22711), [#22708](https://github.com/orgs/supabase/discussions/22708)

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by J0 — APPROVED** [review]

**Comment by omerhochman** [comment]
@kangmingtay @J0 how did you guys validate which one works?

From the error I receive when using signInWithOAuth it looks like you actually need to remove the `/oauth`:

```
oidc: id token issued by a different provider, expected \"https://www.linkedin.com\" got \"https://www.linkedin.com/oauth\"
```

**Comment by J0** [comment]
@omerhochman you can query the `/authorize?provider=linkedin_oidc`

We rolled out the fix recently - do you mind trying again?

**Comment by jonathanjm** [comment]
I have the latest version but still getting this error. "@supabase/ssr": "^0.3.0",
    "@supabase/supabase-js": "^2.42.7",

**Comment by maxontech** [comment]
@jonathanjm, same here.

**Comment by sambowenhughes** [comment]
Still seeing issues with this:

```
   "@supabase/ssr": "latest",
   "@supabase/supabase-js": "latest",
```

**Pull request merged**
