### PR TITLE
fix: Fix reqPath for bypass check for verify EP

### PR DESCRIPTION
**Pull request by angelolamonaca**
## What kind of change does this PR introduce?

Fix reqPath for verify check bypass test

## What is the current behavior?

We are experiencing lot of 403 responses from /v1/verify EP. Supabase is returning "invalid or expired OTP". Correcting this test maybe will raise the cause of our problems. I did not setup the project on my machine, someone can run the test and check if it passes also on verify EP?

## What is the new behavior?

Test is correct.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by angelolamonaca** [comment]
Hopefully fixes https://github.com/orgs/supabase/discussions/29686

**Comment by hf** [comment]
Hey could you open a support ticket at https://supabase.help so we can dig into this a bit more. Feel free to reference this comment so you get to talk to the team directly.

**Comment by angelolamonaca** [comment]
Already done, and original issue was fixed.

Bug was implemented in this commit, removing the strings.ToLower function call on the email
https://github.com/supabase/auth/commit/1af203f92372e6db12454a0d319aad8ce3d149e7#diff-1bee429deb4821de838762a5cce72a874991d044408007a85e1f988e59e0c0c4L566

The fix was implemented here:
https://github.com/supabase/auth/commit/2e9b144a0cbf2d26d3c4c2eafbff1899a36aeb3b

Anyway this test presents a typo, so it's worth merging this PR.

**Review by cstockton — APPROVED** [review]
Looks good, thank you @angelolamonaca

**Pull request merged**
